apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  spec:
    containers:
    - name: apache
      image: arulprasad02/apache2
      ports:
      - containerPort: 3000
